### ISSUE TITLE
Question: Definition of Indicative Features

### ISSUE THREAD

**Issue by Koukyosyumei** [DistributedML/FoolsGold#10]
I am confused about the definition of indicative features. Although the original paper says that FoolsGold measures the cosine similarities of indicative features, which is the gradient of the output layer, the code seems to calculate the cosine similarities of the entire model's gradients.

**Comment by clementfung** [comment]
Hi! 

You're right that, by default, FoolsGold will calculate the cosine similarities across the entire model's gradients.

We have alternate experiments that define significant features in 2 ways (which we call hard and smooth filtering):
1. Using the magnitude of the weights, clip the top k% of the features.
2. Using the magnitude of the weights, proportionally normalize each foolsgold score by its weight. (e.g. multiple by 1 / |w|)

This can be changed at some points in the code. 
Uncommenting here: https://github.com/DistributedML/FoolsGold/blob/master/ML/code/ML_main.py#L100
Using the importance options here: https://github.com/DistributedML/FoolsGold/blob/master/ML/code/model_aggregator.py#L87

I hope this clears up some confusion! Sorry that the code is getting a bit old at this point...

**Comment by bestchai** [comment]
Please reopen if you have any further questions.

**Comment by Koukyosyumei** [comment]
@bestchai @clementfung 

Thank you for your clear explanation!
