### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by Sun2412932156** [DistributedML/FoolsGold#18]
When I run the program, the following error occurs：
Traceback (most recent call last):
  File "F:/project/FoolsGold/ML/data/mnist/parse_mnist.py", line 242, in <module>
    slice_federated()
  File "F:/project/FoolsGold/ML/data/mnist/parse_mnist.py", line 68, in slice_federated
    images, labels = mndata.load_training()
  File "F:\Tools\Anaconda3\envs\foolsgold\lib\site-packages\mnist\loader.py", line 125, in load_training
    ims, labels = self.load(os.path.join(self.path, self.train_img_fname),
  File "F:\Tools\Anaconda3\envs\foolsgold\lib\site-packages\mnist\loader.py", line 247, in load
    with self.opener(path_lbl, 'rb') as file:
  File "F:\Tools\Anaconda3\envs\foolsgold\lib\site-packages\mnist\loader.py", line 239, in opener
    return open(path_fn, *args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '.\\train-labels-idx1-ubyte'

Process finished with exit code 1

**Comment by clementfung** [comment]
Hi Sun, you need to download the MNIST dataset using the instructions here:
https://github.com/DistributedML/FoolsGold#get-the-mnist-data

I've noticed that the link from LeCun is no longer active, but you should be able to download from another link. For example, MNST seems to be available here: https://git-disl.github.io/GTDLBench/datasets/mnist_datasets/

**Comment by Sun2412932156** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
        Hello, Sir. Should I download the following four data sets?
            
        
    
    And then there's still this error.
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Clement ***@***.***>
            
        
      
      
        
         Date 
        
        
        5/3/2023 23:37
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [DistributedML/FoolsGold] Run error (Issue #18)
        
      
    
  
  
Hi Sun, you need to download the MNIST dataset using the instructions here:
https://github.com/DistributedML/FoolsGold#get-the-mnist-data
I've noticed that the link from LeCun is no longer active, but you should be able to download from another link. For example, MNST seems to be available here: https://git-disl.github.io/GTDLBench/datasets/mnist_datasets/

**Comment by Sun2412932156** [comment]
Hello, Sir. I had this error when creating the toxic MNIST 1-7 data step:
`Traceback (most recent call last):
  File "F:/project/FoolsGold/ML/code/misslabel_dataset.py", line 77, in <module>
    main(sys.argv[1:])
  File "F:/project/FoolsGold/ML/code/misslabel_dataset.py", line 15, in main
    if argv[0] == "backdoor":
IndexError: list index out of range`
Please take time out of your busy schedule to help solve doubts. Thanks.

**Comment by Sun2412932156** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hello, I have downloaded the data set according to your instructions, but such an error still occurs.
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Clement ***@***.***>
            
        
      
      
        
         Date 
        
        
        5/3/2023 23:37
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [DistributedML/FoolsGold] Run error (Issue #18)
        
      
    
  
  
Hi Sun, you need to download the MNIST dataset using the instructions here:
https://github.com/DistributedML/FoolsGold#get-the-mnist-data
I've noticed that the link from LeCun is no longer active, but you should be able to download from another link. For example, MNST seems to be available here: https://git-disl.github.io/GTDLBench/datasets/mnist_datasets/

**Comment by clementfung** [comment]
Updated README with new MNIST files.
