### ISSUE TITLE
How to tackle the issuse about missing "from mnist import MNIST" in "parse_mnist.py"?

### ISSUE THREAD

**Issue by XiaoYuanLiuUBC** [DistributedML/FoolsGold#2]
Good days!
I have some questions about the code with a little trouble.
When i download the mnist dataset and run the file "parse_mnist.py" , an error run out with missing the file "MNIST".
Could you please send me the missing file?
Thank you very much!

**Comment by bestchai** [comment]
Please take a look at the code to debug deeper. The [parse_mnist.py file](https://github.com/DistributedML/FoolsGold/blob/master/ML/data/mnist/parse_mnist.py) says the following:

```
#################################################################
#### IMPORTANT!!!
#### Download and gunzip files from http://yann.lecun.com/exdb/mnist/
#################################################################
```

**Comment by XiaoYuanLiuUBC** [comment]
Thank you for your prompt reply.
I regret that I did not make the problem clear. 
The fact is, I have downloaded the MNIST data set  from http://yann.lecun.com/exdb/mnist/ and placed it in ML/data/mnist. However, when I run parse_mnist.py, "ImportError: cannot import name'MNIST' from'mnist' " appears.
I wonder how to solve this problem, if you can help, thank you so much.

**Comment by XiaoYuanLiuUBC** [comment]
Sincerely thank you for your reply!

**Comment by bestchai** [comment]
Hi, did you resolve the issue? If it's resolved I recommend leaving a comment here about how you fixed it, and then closing the issue.

**Comment by XcrossD** [comment]
I encountered this error as well. Apart from following the instruction in the file, you also need to install a module for it.
`pip install python-mnist`
