### ISSUE TITLE
Central server is passing current iteration global model to ALL clients.

### ISSUE THREAD

**Issue by Chakravarti-Baratam** [DistributedML/FoolsGold#4]
https://github.com/DistributedML/FoolsGold/blob/90c2f37b153420b871923fdec397d36a5767aa7e/ML/code/ML_main.py#L111

Here central server is passing current iteration global model to ALL clients. This is typically not the way in Federated Learning. 
Central server randomly picks up few clients. 
If I change the code to pick up few clients randomly, will it effect this algorithm?

**Comment by bestchai** [comment]
If you change the code, of course it will have effect. This part of the algorithm is especially important to get right. Make sure that you test your changes.
